### ISSUE TITLE
optional session_id considerations

### ISSUE THREAD

**Issue by evq** [codahale/cpace#1]
Hey there, I also have a library [1] that also combines a CPACE like PAKE protocol with STROBE - very cool to see that someone else had a similar idea! 

I noticed that your library currently mentions the session id is optional in a comment and a commit string says an empty string can be passed.

I wanted to pass along a replay attack I recently realized can occur in my library and other CPACE-like implementations if the session id were omitted or not enforced to be unique in a setting that allows concurrent sessions. (An attacker may also replay a user's own point within the same session, though this can be detected through key confirmation challenges.) These are old SPEKE issues that won't impact most use cases, but I'm always in favor of building misuse resistance into cryptographic implementations. These problems are particularly pronounced in fully symmetric variants of the protocol - because the identities are typically lexicographically ordered when being bound to the transcript.

The way I've attempted to mitigate these issues while keeping symmetry (even in the face of a non-unique or omitted session id) is as follows:

1. I split the transcript into two parts (tx/rx), add the identities and ephemerals in to each in the order that they observe occurring (i.e. both parties add their own identity and ephemeral to their tx transcript first). If a replay across concurrent sessions occurs, i.e. A attempts to connect to B, C replays A's request to initiate a concurrent session as if they were B ); the tx transcript A->B in session 1 will not match up with the rx transcript in session 2 ( A would expect B->A ) and likewise the rx transcript in 1 will not match tx in 2.
2. I've included the user's identity in the handshake packet and included a sanity check when consuming a handshake that the identity is different than one's own. This is mainly needed to handle use cases where the other user's identity may not be known up front. It also seems important to consider cases where identity may be controlled by an attacker ( some types of network addresses may fall into this category ) and that perhaps there is some importance to using a self determined identity that cannot change while handshakes are in progress ( in cases where as suitable id does not already exist, a simple suggested pattern here may be to generate a static random self ID on application or device startup ala lazy_static ). Network identities can and should be bound into the transcript in addition to self determined identity and can be done so according to lexicographical order so long as self identity is added according to 1.

[1] https://github.com/evq/yodel

**Comment by codahale** [comment]
Glad to see more folks are using STROBE! Thanks for reaching out.

It’s been a while since I’ve thought about this particular library, and I’ll be the first to admit I’m no SPEKE expert, but I don’t think I understand what replay attack you’re referring to.

Assume we’ve got an entirely above-board key agreement between Alice and Bea which doesn’t use a session ID. Alice adds her own identity as associated data, then adds Bea’s identity as associated data. She keys the protocol with their shared password, generates a random ephemeral scalar `dA`, extracts a generator point `g` from the PRF output, and sends Bea `g*dA`. Meanwhile, Bea does the same thing on her side, but with a different scalar, `dB`. They exchange points, include both points as associated data, and both calculate the shared secret point `g*dA*dB`. They both key their protocols with the shared secret point and Alice sends Bea the message `I owe you $100`. Now let’s assume Mallory was listening to the whole thing and recorded `g*dA`, `g*dB`, and the encrypted form of `I owe you $100` and she wants to convince Bea that Alice actually owes her $200.

Assume Mallory tricks Bea into believing that her identity is Alice, so Bea’s transcript starts out identical to the first conversation and uses the same generator point `g`. She creates a new scalar, `dB’`, and sends `g*dB’`. Mallory sends the `g*dA` she stole from Alice. Bea records both transmitted points as associated data, at which point her transcript diverges from the original conversation because `dB` and `dB’` are different. Bea calculates what she thinks is the shared secret point, `g*dA*dB’`, and keys her protocol with it. Mallory sends the `I owe you $100` she stole from Alice, but Bea can’t decrypt it, since her second transcript is nothing like her first transcript. (I’m assuming authenticated encryption here b/c it’s the middle of 2021.)

What am I missing here?

**Comment by evq** [comment]
The issue is easiest understood in a scenario where Bea does not participate at all. Alice thinks she is attempting to initiate an exchange with Bea, however it never reaches Bea. Instead our network adversary Mallory uses Alice's own point to initiate a separate exchange with Alice as if she were Bea.

At this point from Alice's perspective she believes there are two parallel sessions with Bea. Alice's response point from the second session can be used to complete the first and vice versa - key confirmation can also be bypassed similarly. As a result Alice authenticates both sessions as Bea despite her not being involved at all and in reality has a session with herself.

Whether this matters or not depends heavily on the protocol, but canonical example attack at this point goes something like: Assume all identities are automated agents that blindly follow messages from an authenticated session. Alice attempts to send Bea the authenticated message `send Carol $100`, Alice receives this from Malory in the other session, believes it to be from Bea and herself sends Carol $100.

```
    #[test]
    fn fake_exchange() {
        let alice = Exchanger::new(b"Alice", b"Bea", b"secret", b"");
        let y_alice = alice.send();

        let alice2 = Exchanger::new(b"Alice", b"Bea", b"secret", b"");
        let y_alice2 = alice2.send();

        let mut alice = alice.receive(y_alice2);
        let mut bea = alice2.receive(y_alice);

        let mut prf_a = [0u8; 16];
        alice.prf(&mut prf_a, false);

        let mut prf_b = [0u8; 16];
        bea.prf(&mut prf_b, false);

        assert_ne!(prf_b, prf_a);
    }
```

**Comment by codahale** [comment]
Oh, _very_ cool! I’d been thinking of this as a standard client/server protocol, but the peer-to-peer aspect opens that up.

**Comment by evq** [comment]
Out of curiosity - when you were implementing, do you remember which papers and/or resources were you using as references? The IETF draft has diverged somewhat from the original literature and seems to now have an explicit initiator and responder, I'm having trouble finding an up to date resource for the fully symmetric CPACE protocol. It's confusing to me that from what I've seen there is no mention of the symmetric variant in the draft yet all the papers seem to deal in it exclusively.

**Comment by codahale** [comment]
Pretty sure I was going off of [draft-haase-cpace-00](https://tools.ietf.org/id/draft-haase-cpace-00.html).

**Comment by codahale** [comment]
I figured I’d keep things simple and use initiator/responder roles to order the transcripts instead of lexical ordering. Again, thanks for explaining that replay attack to me. I appreciate it.

If you’d like to see some more truly appalling STROBE stuff, check out my [veil-rs](https://github.com/codahale/veil-rs/) project. It’s either an attempt to reinvent the PGP wheel using 21st century parts or an art project. I can’t decide which.
